language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  -
  - RACK_VERSION=1.3.0
  - RACK_VERSION=1.4.0
  - RACK_VERSION=1.5.0
  - RACK_VERSION=1.6.0

script: "bundle exec rake spec"

branches:
  only:
    - master
