language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - gemfiles/gemfile
  - gemfiles/rack.1.4.x.gemfile
  - gemfiles/rack.1.3.x.gemfile

script: "bundle exec rake spec"

branches:
  only:
    - master
